export const CLOSE_OPENED_DROPDOWNS = 'CLOSE_OPENED_DROPDOWNS';

// COMPANY
export const SET_COMPANY_NAME = 'SET_COMPANY_NAME';
export const SET_COMPANY_STREET = 'SET_COMPANY_STREET';
export const SET_COMPANY_POSTALCODE = 'SET_COMPANY_POSTALCODE';
export const SET_COMPANY_CITY = 'SET_COMPANY_CITY';
export const SET_COMPANY_COUNTRY = 'SET_COMPANY_COUNTRY';

export const SET_CHOSEN_COMPANY_DETAILS = 'SET_CHOSEN_COMPANY_DETAILS';

// TAX
export const SET_CHOSEN_TAX_DETAILS = 'SET_CHOSEN_TAX_DETAILS';

// PRODUCT
export const SET_CHOSEN_PRODUCT_DETAILS = 'SET_CHOSEN_PRODUCT_DETAILS';

// INVOICE
export const SET_CHOSEN_INVOICE_DETAILS = 'SET_CHOSEN_INVOICE_DETAILS';

// CUSTOMER
export const SET_CHOSEN_CUSTOMER_DETAILS = 'SET_CHOSEN_CUSTOMER_DETAILS';