export const CLOSE_OPENED_DROPDOWNS = 'CLOSE_OPENED_DROPDOWNS';

// COMPANY
export const SET_CHOSEN_COMPANY_DETAILS = 'SET_CHOSEN_COMPANY_DETAILS';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';
export const ADD_COMPANY = 'ADD_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';

// TAX
export const SET_CHOSEN_TAX_DETAILS = 'SET_CHOSEN_TAX_DETAILS';
export const REMOVE_TAX = 'REMOVE_TAX';
export const ADD_TAX = 'ADD_TAX';
export const UPDATE_TAX = 'UPDATE_TAX';

// PRODUCT
export const SET_CHOSEN_PRODUCT_DETAILS = 'SET_CHOSEN_PRODUCT_DETAILS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

// INVOICE
export const SET_CHOSEN_INVOICE_DETAILS = 'SET_CHOSEN_INVOICE_DETAILS';
export const REMOVE_INVOICE = 'REMOVE_INVOICE';
export const ADD_INVOICE = 'ADD_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';

// CUSTOMER
export const SET_CHOSEN_CUSTOMER_DETAILS = 'SET_CHOSEN_CUSTOMER_DETAILS';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';