export const CLOSE_OPENED_DROPDOWNS = 'CLOSE_OPENED_DROPDOWNS';

// COMPANY
export const SET_CHOSEN_COMPANY_DETAILS = 'SET_CHOSEN_COMPANY_DETAILS';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';
export const ADD_COMPANY = 'ADD_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';

// TAX
export const SET_CHOSEN_TAX_DETAILS = 'SET_CHOSEN_TAX_DETAILS';
export const REMOVE_TAX = 'REMOVE_TAX';

// PRODUCT
export const SET_CHOSEN_PRODUCT_DETAILS = 'SET_CHOSEN_PRODUCT_DETAILS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';

// INVOICE
export const SET_CHOSEN_INVOICE_DETAILS = 'SET_CHOSEN_INVOICE_DETAILS';
export const REMOVE_INVOICE = 'REMOVE_INVOICE';

// CUSTOMER
export const SET_CHOSEN_CUSTOMER_DETAILS = 'SET_CHOSEN_CUSTOMER_DETAILS';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';