export const SET_CHOSEN_COMPANY_DETAILS = 'SET_CHOSEN_COMPANY_DETAILS';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';
export const ADD_COMPANY = 'ADD_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const FETCH_COMPANIES = 'FETCH_COMPANIES';