export const SET_CHOSEN_CUSTOMER_DETAILS = 'SET_CHOSEN_CUSTOMER_DETAILS';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';