export const SET_CHOSEN_INVOICE_DETAILS = 'SET_CHOSEN_INVOICE_DETAILS';
export const REMOVE_INVOICE = 'REMOVE_INVOICE';
export const ADD_INVOICE = 'ADD_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const FETCH_INVOICES = 'FETCH_INVOICES';