export const SET_CHOSEN_PRODUCT_DETAILS = 'SET_CHOSEN_PRODUCT_DETAILS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';